### ISSUE TITLE
IDE Error occurs

### ISSUE THREAD

**Issue by arnerescheleit** [Mr-Pine/SimpleCodeTester-IntelliJ-Plugin#11]
sobald ich versuche meinen code mit dem plugin hochzuladen passiert das

![image](https://user-images.githubusercontent.com/108663827/227468562-59d9320e-c400-413e-8ed2-009fc5aae783.png)

**Comment by Mr-Pine** [comment]
(Fast) Das Problem ist, dass du ein extra src Module hast, in dem dein Sources Root liegt. Das Plugin schaut aber im ersten Modul, das es findet nach dem Sources Root (also hier `programming_final02`) und das hat keins. Die Projektstruktur zu fixen sollte auch das Problem lösen. Ich bin mir auch nicht sicher, ob Artemis so eine Struktur überhaupt akzeptiert
